// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum.proto

#ifndef PROTOBUF_enum_2eproto__INCLUDED
#define PROTOBUF_enum_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace CBR {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_enum_2eproto();
void protobuf_AssignDesc_enum_2eproto();
void protobuf_ShutdownFile_enum_2eproto();


enum ErrorCode {
  ERR_SUCCESS = 0,
  ERR_FAILED = 1,
  ERR_NAME_INVALID = 2,
  ERR_PASSWARD_INVALID = 3,
  ERR_NAME_EXISTING = 4,
  ERR_NAME_TOO_SHORT = 5,
  ERR_NAME_TOO_LONG = 6,
  ERR_NAME_HAS_INVALID_CHAR = 7,
  ERR_PASSWARD_TOO_SHORT = 8,
  ERR_PASSWARD_TOO_LONG = 9,
  ERR_PASSWARD_HAS_INVALID_CHAR = 10,
  ERR_PASSWARD_ERROR = 11,
  ERR_TOKEN_INVALID = 12,
  ERR_SESSION_INVALID = 13,
  ERR_STATE_INVALID = 14,
  ERR_ACCOUNT_NOTEXIST = 15,
  ERR_REDIS_NOTDATA = 16,
  ERR_MYSQL_NODATA = 17
};
bool ErrorCode_IsValid(int value);
const ErrorCode ErrorCode_MIN = ERR_SUCCESS;
const ErrorCode ErrorCode_MAX = ERR_MYSQL_NODATA;
const int ErrorCode_ARRAYSIZE = ErrorCode_MAX + 1;

enum DBOperType {
  DBOper_Insert = 1,
  DBOper_Update = 2,
  DBOper_Del = 3,
  DBOper_DelAll = 4,
  DBOper_ReplaceId = 5
};
bool DBOperType_IsValid(int value);
const DBOperType DBOperType_MIN = DBOper_Insert;
const DBOperType DBOperType_MAX = DBOper_ReplaceId;
const int DBOperType_ARRAYSIZE = DBOperType_MAX + 1;

enum Channel {
  CHANNEL_GUEST = 0,
  CHANNEL_COMMON = 1,
  CHANNEL_CHANNEL = 2
};
bool Channel_IsValid(int value);
const Channel Channel_MIN = CHANNEL_GUEST;
const Channel Channel_MAX = CHANNEL_CHANNEL;
const int Channel_ARRAYSIZE = Channel_MAX + 1;

enum LoginStatus {
  LOGIN_STATUS_INVALID = 1,
  LOGIN_STATUS_AUTH = 2,
  LOGIN_STATUS_FIN = 3
};
bool LoginStatus_IsValid(int value);
const LoginStatus LoginStatus_MIN = LOGIN_STATUS_INVALID;
const LoginStatus LoginStatus_MAX = LOGIN_STATUS_FIN;
const int LoginStatus_ARRAYSIZE = LoginStatus_MAX + 1;

enum MatchStatus {
  MATCH_STATUS_NONE = 1,
  MATCH_STATUS_MATCHING = 2,
  MATCH_STATUS_MATCHED = 3,
  MATCH_STATUS_FIGHTWAIT = 4,
  MATCH_STATUS_CHOICEHERO = 5,
  MATCH_STATUS_FIGHTING = 6,
  MATCH_STATUS_END = 7
};
bool MatchStatus_IsValid(int value);
const MatchStatus MatchStatus_MIN = MATCH_STATUS_NONE;
const MatchStatus MatchStatus_MAX = MATCH_STATUS_END;
const int MatchStatus_ARRAYSIZE = MatchStatus_MAX + 1;

enum PVPStatus {
  PVP_STATUS_NONE = 0,
  PVP_STATUS_FREE = 1,
  PVP_STATUS_BATTLE_PREPARE = 2,
  PVP_STATUS_BATTLE_WAITING = 3,
  PVP_STATUS_BATTLE_CHOICEHERO = 4,
  PVP_STATUS_BATTLE_FIGHTING = 5,
  PVP_STATUS_BATTLE_END = 6
};
bool PVPStatus_IsValid(int value);
const PVPStatus PVPStatus_MIN = PVP_STATUS_NONE;
const PVPStatus PVPStatus_MAX = PVP_STATUS_BATTLE_END;
const int PVPStatus_ARRAYSIZE = PVPStatus_MAX + 1;

enum ENUM_MATCH_TYPE {
  MATCH_TYPE_BATTLEROYALE = 0,
  MATCH_TYPE_ANNIHILATION = 1
};
bool ENUM_MATCH_TYPE_IsValid(int value);
const ENUM_MATCH_TYPE ENUM_MATCH_TYPE_MIN = MATCH_TYPE_BATTLEROYALE;
const ENUM_MATCH_TYPE ENUM_MATCH_TYPE_MAX = MATCH_TYPE_ANNIHILATION;
const int ENUM_MATCH_TYPE_ARRAYSIZE = ENUM_MATCH_TYPE_MAX + 1;

// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace CBR

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_enum_2eproto__INCLUDED
